version: "3"
networks:
  backend:
    driver: ${NETWORKS_DRIVER}

volumes:
  app_log:
    driver: ${VOLUMES_DRIVER}
  nginx_log:
    driver: ${VOLUMES_DRIVER}

services:
### Backend Server #########################################
  app:
    build:
      context: ../
      dockerfile: devops/app/Dockerfile
    volumes:
      - app_log:/var/log
      - ${APP_PATH}:/app
    ports:
      - "${APP_SUPERUSER_PORT}:9001"
    environment:
      - SUPERVISOR_USERNAME=${SUPERVISOR_USERNAME}
      - SUPERVISOR_PASSWORD=${SUPERVISOR_PASSWORD}
    networks:
      - backend

### NGINX Server #########################################
  nginx:
    build:
      context: ./nginx
      args:
      - APP_UPSTREAM_CONTAINER=${APP_UPSTREAM_CONTAINER}
      - APP_UPSTREAM_PORT=${APP_UPSTREAM_PORT}
    volumes:
      - nginx_log:/var/log
      - ${NGINX_SITES_PATH}:/etc/nginx/sites-available
    ports:
      - "${NGINX_HOST_HTTP_PORT}:80"
      - "${NGINX_HOST_HTTPS_PORT}:443"
    depends_on:
      - app
    networks:
      - backend
